version: '3.1'

services:

  front-end:
    image: php:apache
    container_name: front
    restart: always
    ports:
      - 8080:80
    environment:
      - USERNAME=toto
      - PASSWORD=python
    volumes:
      - ./website:/var/www/html
    networks:
      - control
    depends_on:
      - api

  api:
    image: simple-api:v1
    container_name: api
    restart: always
    volumes:
      - ./simple_api/student_age.json:/data/student_age.json
    ports:
      - 5000:5000
    networks:
      - control
networks:
  control: